### ISSUE TITLE
App not reading DSU Manager's QR

### ISSUE THREAD

**Issue by Mootangg** [breeze2/dsu-controller-guides#18]
Somehow, i got the app reading the QR succesfully but DSU Manager **doesn't detect my device and neither my IP Address and Port**, can somebody help? :( 

Im using Dolphin Emulator, DSU Manager and ViGEmBus (T T)

**Comment by breeze2** [comment]
Try to manual input ip:port of DSU Controller.
![image](https://github.com/breeze2/dsu-controller-guides/assets/5266711/9c719b4e-ceef-4238-ba60-057e4f8ea978)


[More detail](https://github.com/breeze2/dsu-manager-guides/issues/1)
This should be a bug and will be fixed in the next version of DSUManager.

**Comment by breeze2** [comment]
Make sure DSUManager can communicate through Windows Firewall, please refer to this video, [How to Allow a program to communicate through Windows Firewall for Microsoft](https://www.dell.com/support/contents/en-us/videos/videoplayer/how-to-allow-a-program-to-communicate-through-windows-firewall-for-microsoft/6079812902001).
